# Generated by Django 3.2 on 2023-05-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
