# Generated by Django 3.2 on 2023-05-04 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_uservideointermediate'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 19, 46, 47, 154527)),
        ),
    ]
