# Generated by Django 3.2.18 on 2023-05-04 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_video_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 2, 44, 18, 274691)),
        ),
    ]
