# Generated by Django 3.2.18 on 2023-05-05 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_video_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='upload_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 5, 17, 34, 18, 761173)),
        ),
    ]
