# Generated by Django 4.2 on 2023-04-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Company", "verbose_name_plural": "Companies"},
        ),
        migrations.AlterModelOptions(
            name="vacancy",
            options={"verbose_name": "Vacancy", "verbose_name_plural": "Vacancies"},
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="company",
            name="city",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.company"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name="vacancy", name="salary", field=models.FloatField(default=0),
        ),
    ]
